name: Github Pages for Docs

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    # Allow this job to push changes to your repository
    permissions:
      contents: write

    steps:
      - name: Check out your repository using git
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Not using npm? Change `npm ci` to `yarn install` or `pnpm i`
      - name: Install dependencies
        run: pip install mkdocs-material

      # Not using npm? Change `npm run build` to `yarn build` or `pnpm run build`
      - name: Build Documentation
        run: mkdics build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # `./dist` is the default Astro build directory.
          # If you changed that, update it here too.
          publish_dir: ./site
